name: Pysh-check
run-name: ${{ github.actor }} Pull Request pysh-check
on: 
  push:
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  run-pysh-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # Install pyshcheck tooling
      - name: Install (apt-get) dependencies
        run: sudo apt-get install black pycodestyle pydocstyle shellcheck python3
      - uses: actions/checkout@v4
        with:
          repository: 'PelionIoT/scripts-internal'
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: ../scripts-internal/pysh-check/pysh-check.sh --workdir .
