name: Pysh-check
run-name: ${{ github.actor }} Pull Request pysh-check
on: [push]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  run-pysh-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Install pyshcheck tooling
      - name: Install (apt-get) dependencies
        run: sudo apt-get install black pycodestyle pydocstyle shellcheck python3
      # git instead of rules to use access token
      - name: Clone scripts-internal
        run: |
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf "https://github"
          git clone git@github.com:PelionIoT/scripts-internal.git
          echo . >scripts-internal/.nopyshcheck
      - run: scripts-internal/pysh-check/pysh-check.sh --workdir .
